# Netlify configuration
[build]
  publish = "."

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/blog-desarrollo-medida"
  to = "/blog-desarrollo-medida.html"
  status = 200

[[redirects]]
  from = "/blog-seo-regional"
  to = "/blog-seo-regional.html"
  status = 200

[[redirects]]
  from = "/terminos"
  to = "/terminos.html"
  status = 200

[[redirects]]
  from = "/privacidad"
  to = "/privacidad.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "geolocation=(self), microphone=(), camera=()"
